### ISSUE TITLE
docker-compose installation fails for Ubuntu 16.04

### ISSUE THREAD

**Issue by caffeinatedpixel** [activecm/shell-lib#18]
`install_docker.sh` fails on Ubuntu 16.04.

![image](https://user-images.githubusercontent.com/24681559/160712009-434c71ce-78f3-4bfc-8db3-a620479b9ce0.png)

Fix the incompatible python version for pip by installing the last compatible version of pip for python3.5 instead of the latest available.

**Comment by Zalgo2462** [comment]
We probably want to include the `-H` flag on the calls to sudo `pip` as well. This should get rid of the error messages above and ensure that root-owned files don't end up in the user's home directory.

**Comment by Zalgo2462** [comment]
It might be easier to hack on the commented out install code at 
https://github.com/activecm/shell-lib/blob/fa6ee87ebcab1a056ba3607c2d576e481faab3b9/docker/install_docker.sh#L149-L152

If we un-comment this section and change it to install into `/usr/local/bin` rather than `/usr/bin`, the outcome should be the same as installing with pip.
